-- Historical note: this migration originally marked three specific members as
-- 'family' rate (FY2026: $96 vs. $120 individual) by hard-coded email, matching
-- a one-time treasurer request. That hard-coded a personal email address for a
-- billing decision, which does not belong in a public repository (see CLAUDE.md
-- -> "No Personal Data in the Repository").
--
-- Production already carries the intended dues_category = 'family' values for
-- those members from when this migration first ran; removing the seed here
-- does not undo that. Any future family-rate designation should be made
-- through the admin Dues UI (per-member dues_category control — see
-- src/components/admin/dues-category-control.tsx and
-- src/app/api/admin/dues/[memberId]/category/route.ts), not a migration.
--
-- This file is kept (rather than deleted) only so the migrations directory's
-- numbering stays contiguous; it is intentionally a no-op on every run.
SELECT 1;
